# charts/mywebsite/templates/app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  labels:
    app: mywebsite
spec:
  # Pulls the replica count from values.yaml
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "pgdb"
        - name: DB_NAME
          value: "restaurants"
        # Reference the K8s Secret created by ESO
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-credentials-k8s # Name defined in ExternalSecret target
              key: db_username         # Key defined in ExternalSecret data
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials-k8s
              key: db_password