# charts/mywebsite/templates/app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  labels:
    app: mywebsite
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "{{ .Values.rds.endpoint }}"
        - name: DB_NAME
          value: "{{ .Values.rds.dbName }}"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: rds-config
              key: POSTGRES_USER # Keep ConfigMap key, but change ENV name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: postgres-password # Keep Secret key, but change ENV name