rds:
  endpoint: "cloudride-legacy-db.c0kc8dxradrc.us-west-2.rds.amazonaws.com"
  username: "postgres"
  password: "example"
  dbName:   "restaurants"

replicaCount: 2
image:
  repository: 753392824297.dkr.ecr.us-west-2.amazonaws.com/liorm-cloudride
  pullPolicy: IfNotPresent
  tag: "latest"
