rds:
  endpoint: "${rds_endpoint}"
  username: "${db_username}"
  password: "${db_password}"
  dbName:   "${db_name}"

replicaCount: 2
image:
  repository: 753392824297.dkr.ecr.us-west-2.amazonaws.com/liorm-cloudride
  pullPolicy: IfNotPresent
  tag: "latest"
